version: '3.9'
services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: cloud
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7
    restart: always
  web:
    build: .
    ports:
      - "443:8000"
    environment:
      POSTGRES_URL: postgresql+asyncpg://postgres:postgres@postgres/cloud
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - postgres
      - redis
volumes:
  pgdata:
