services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-cloud}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-cloudpass}
      POSTGRES_DB: ${POSTGRES_DB:-cloud_db}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks: [backend]

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    networks: [backend]

  broker:
    image: eclipse-mosquitto:2
    restart: unless-stopped
    ports: ["1884:1883"]
    networks: [backend]

  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    env_file: .env
    ports: ["8082:8000"]
    depends_on: [db, redis, broker]
    restart: unless-stopped
    networks: [backend]

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python", "-m", "app.worker"]
    env_file: .env
    depends_on: [db, redis, broker]
    restart: unless-stopped
    networks: [backend]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports: ["8083:80"]
    depends_on: [api]
    restart: unless-stopped
    networks: [backend]

  frontend_cloud:
    build:
      context: ./frontend_cloud
      dockerfile: Dockerfile
    depends_on: [api]
    restart: unless-stopped
    networks: [backend]

  frontend_admin:
    build:
      context: ./frontend_admin
      dockerfile: Dockerfile
    depends_on: [api]
    restart: unless-stopped
    networks: [backend]

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"   # HTTP redirect only
      - "443:443" # HTTPS only
    volumes:
      - ./nginx/conf.d/cloud.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl/certs:/etc/ssl/certs:ro
      - ./ssl/private:/etc/ssl/private:ro
    depends_on:
      - frontend_cloud
      - frontend_admin
      - api
    restart: unless-stopped
    networks: [backend]

volumes:
  db_data:

networks:
  backend:
