version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: battery_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:7

  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      POSTGRES_URL: postgresql+asyncpg://user:password@db/battery_db
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
